### PR TITLE
Leave poor grasshopper.com alone

### PR DESCRIPTION
**Pull request by mrvisser**
I have a thing using non-obvious sample URLs as sample/default URLs, especially when they resolve to something on the internet, and especially especially when they resolve to what looks to be valid existing company domains.

We can do all the things we need with `/etc/hosts` with `*.local` domains which are more common for things that we intend to resolve locally (e.g., default URLs), so it's better a bit more clear about the intention when we default to `*.local`s.

### CODE REVIEW

**Comment by mrvisser** [comment]
I've also made it so that the hostnames specified in `config.js` don't break any tests, and it's now not necessary for the tests to override the configured hosts for anything.

**Comment by mrvisser** [comment]
Assigned to @simong for review

**Comment by simong** [comment]
PR looks good. Feel free to merge after rebasing and fixing up/explaining that one comment

**Comment by simong** [comment]
Merged this into master manually

**Pull request closed without merging**
