### PR TITLE
Allow you to specify a serie when creating an event

### PR DESCRIPTION
**Pull request by simong**
Builds on #30

### CODE REVIEW

**Comment by nicolaasmatthijs** [comment]
Left some very minor feedback on the final commit. Back to @simong for follow-up

**Comment by simong** [comment]
Followed-up, back to @nicolaasmatthijs

**Comment by nicolaasmatthijs** [comment]
@simong : Can you rebase this against master?

**Comment by simong** [comment]
@nicolaasmatthijs: I did, I'm not sure why Github is still showing the old commits. I'll resend the PR

**Pull request closed without merging**
